# Generated by Django 4.1.2 on 2022-10-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleWithCustomDrilldown",
            fields=[],
            options={
                "verbose_name": "Sale model with custom drilldown",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sales.sale",),
        ),
        migrations.CreateModel(
            name="SaleWithDrilldown",
            fields=[],
            options={
                "verbose_name": "Sale model with default drilldown",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sales.sale",),
        ),
    ]
